export {
  appendAuthCookiesFromSetAll,
  authCookiesFromDocumentCookie,
  authCookieWriter,
  copySetCookieHeaders,
  expireHostOnlyAuthCookies,
  getAuthCookieOptions,
  hasSupabaseAuthCookie,
  hostOnlyExpireSetCookieHeader,
  isSupabaseAuthCookieName,
  mergeAuthCookieOptions,
  parentDomainSetCookieHeader,
  rehomeAuthCookiesToParentDomain,
  rehomeReadableAuthCookiesInBrowser,
  resolveAuthCookieDomain,
  resolveRequestHostname,
  serializeAuthSetCookie,
  supabaseProjectRefFromUrl,
  type AuthCookieOptions,
  type AuthCookieWriter,
} from "./cookieOptions";

export {
  AUTH_ACCEPT_PATH,
  AUTH_CALLBACK_PATH,
  AUTH_CATCH_PATH,
  AUTH_CONTINUE_PATH,
  AUTH_NEXT_SPEICHER_CALCULATE,
  AUTH_SIGN_IN_PATH,
  AUTH_SIGN_OUT_PATH,
  getHubAuthContinueUrl,
  getHubKontoUrl,
  getHubLoginUrlForSpeicherCalculate,
  getHubOrigin,
  getHubSignupUrl,
  getSpeicherGrenzeCalculateUrl,
  getSpeicherGrenzeOrigin,
  isAllowedHubFormOrigin,
  isAllowedSessionHandoffOrigin,
  isAllowedSessionHandoffRequest,
  isHubAuthMutationPath,
  isSpeicherAuthHandoffPath,
  parseAuthNextParam,
  resolvePostLoginRedirect,
  sanitizeNextPath,
} from "./redirects";

export {
  decodeSessionHandoffPayload,
  encodeSessionHandoffPayload,
} from "./handoff";
