export {
  SHARED_AUTH_COOKIE_NAME,
  appendAuthCookiesFromSetAll,
  authCookieWriter,
  copySetCookieHeaders,
  expireAuthCookiesForLogout,
  expireLegacyAuthCookies,
  getAuthCookieOptions,
  hasSupabaseAuthCookie,
  isLegacyAuthCookieName,
  isSharedAuthCookieName,
  isSupabaseAuthCookieName,
  mergeAuthCookieOptions,
  redirectWithAuthCookies,
  resolveAuthCookieDomain,
  resolveRequestHostname,
  serializeAuthSetCookie,
  supabaseProjectRefFromUrl,
  type AuthCookieOptions,
  type AuthCookieWriter,
} from "./cookieOptions";

export {
  AUTH_CALLBACK_PATH,
  AUTH_NEXT_SPEICHER_CALCULATE,
  AUTH_NEXT_SPEICHER_RESULT_PREFIX,
  AUTH_RETURN_SPEICHER,
  AUTH_SIGN_IN_PATH,
  AUTH_SIGN_UP_PATH,
  AUTH_SIGN_OUT_PATH,
  getHubKontoUrl,
  getHubLoginUrlForSpeicherCalculate,
  getHubLoginUrlForSpeicherResult,
  getHubOrigin,
  getHubSignOutUrl,
  getHubSignupUrl,
  getSpeicherGrenzeCalculateUrl,
  getSpeicherGrenzeOrigin,
  getSpeicherGrenzeResultUrl,
  isAllowedHubFormOrigin,
  isAllowedHubSignOutOrigin,
  isHubAuthMutationPath,
  isPvNavigatorUuid,
  parseAuthNextParam,
  resolvePostLoginRedirect,
  resolvePostLoginLocation,
  resolvePostLogoutLocation,
  sanitizeNextPath,
} from "./redirects";
