export {
  appendAuthCookiesFromSetAll,
  authCookieWriter,
  copySetCookieHeaders,
  expireHostOnlyAuthCookies,
  getAuthCookieOptions,
  hasSupabaseAuthCookie,
  hostOnlyExpireSetCookieHeader,
  isSupabaseAuthCookieName,
  mergeAuthCookieOptions,
  parentDomainSetCookieHeader,
  rehomeAuthCookiesToParentDomain,
  resolveAuthCookieDomain,
  resolveRequestHostname,
  serializeAuthSetCookie,
  supabaseProjectRefFromUrl,
  type AuthCookieOptions,
  type AuthCookieWriter,
} from "./cookieOptions";

export {
  AUTH_CONTINUE_PATH,
  AUTH_NEXT_SPEICHER_CALCULATE,
  AUTH_SIGN_IN_PATH,
  AUTH_SIGN_OUT_PATH,
  getHubAuthContinueUrl,
  getHubKontoUrl,
  getHubLoginUrlForSpeicherCalculate,
  getHubOrigin,
  getHubSignupUrl,
  getSpeicherGrenzeCalculateUrl,
  getSpeicherGrenzeOrigin,
  isAllowedHubFormOrigin,
  isHubAuthMutationPath,
  parseAuthNextParam,
  resolvePostLoginRedirect,
  sanitizeNextPath,
} from "./redirects";
